# Generated by Django 5.2.8 on 2025-11-23 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pet_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='shelter_pet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_pet_id', models.IntegerField()),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_species', models.CharField(max_length=10)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('applicant_address', models.TextField()),
                ('family_members', models.TextField(help_text='Number and ages of family members')),
                ('previous_pets', models.TextField(help_text='Experience with previous pets')),
                ('home_type', models.CharField(help_text='Apartment, house, etc.', max_length=100)),
                ('yard_info', models.TextField(help_text='Information about yard/outdoor space')),
                ('work_schedule', models.TextField(help_text='Work hours and schedule')),
                ('pet_alone_time', models.TextField(help_text='How long pet would be alone daily')),
                ('vet_contact', models.TextField(blank=True, help_text='Veterinarian contact information')),
                ('references', models.TextField(help_text='Personal references')),
                ('message', models.TextField(blank=True, help_text='Additional comments')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Adoption Completed')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
