# Generated by Django 5.2.8 on 2025-11-24 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adoptionrequest_shelter_pet_id_adoptionapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_appointment_id', models.IntegerField(blank=True, null=True)),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(default='dog', max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('vet_name', models.CharField(default='Dr. Unknown', max_length=255)),
                ('appointment_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vet Appointment',
                'verbose_name_plural': 'Vet Appointments',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
