# Generated by Django 4.2.9 on 2025-11-24 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['-vaccination_date'], 'verbose_name': 'Vaccine Record', 'verbose_name_plural': 'Vaccine Records'},
        ),
        migrations.AlterModelOptions(
            name='vet',
            options={'ordering': ['name'], 'verbose_name': 'Veterinarian', 'verbose_name_plural': 'Veterinarians'},
        ),
        migrations.AddField(
            model_name='pet',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='vet_profiles/'),
        ),
        migrations.AddField(
            model_name='vet',
            name='working_hours_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='vet',
            name='working_hours_start',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes')], default=30),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('reptile', 'Reptile'), ('other', 'Other')], default='dog', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.CharField(choices=[('rabies', 'Rabies'), ('distemper', 'Distemper'), ('parvo', 'Parvovirus'), ('hepatitis', 'Hepatitis'), ('leptospirosis', 'Leptospirosis'), ('bordetella', 'Bordetella'), ('feline_leukaemia', 'Feline Leukaemia'), ('feline_viral_rhinotracheitis', 'Feline Viral Rhinotracheitis'), ('canine_parainfluenza', 'Canine Parainfluenza'), ('lyme', 'Lyme Disease')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vet',
            name='specialization',
            field=models.CharField(choices=[('general', 'General Practice'), ('surgery', 'Surgery'), ('dentistry', 'Dentistry'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('emergency', 'Emergency Care')], default='general', max_length=50),
        ),
    ]
