# Generated by Django 4.2.9 on 2025-11-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='external_pet_id',
            field=models.IntegerField(blank=True, help_text='ID of pet from external system (e.g., Shelter Database) - Optional', null=True, unique=True),
        ),
    ]
